import 'package:github/github.dart' as gh;
import 'package:meta/meta.dart';

class DartHub {
  DartHub(this.client);

  Future<void> init() async {
    final gh.CurrentUser user = await client.users.getCurrentUser();
    print('Hello ${user.name}');
    print(
        '${client.rateLimitLimit} out of ${client.rateLimitRemaining} requests remaining.');
  }

  final gh.GitHub client;

  Future<gh.Repository> createRepository({
    @required String name,
    String description = 'This repository was generated by DartHub.',
  }) async {
    final gh.CreateRepository cr = gh.CreateRepository(
      name,
      autoInit: false,
      description: description,
      private: false,
    );
    final gh.Repository repo = await client.repositories.createRepository(cr);
    print('Created repo ${repo.name} at ${repo.htmlUrl}\n');
    print('git remote add origin ${repo.sshUrl}');
    print('git push --set-upstream origin master');
    return repo;
  }
}
